/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distribucion_aerolineas_udla;

import Entidades.Asiento;
import Entidades.Registro;
import GestorInformacion.GestorInformacion;
import Listas.Lista;
import javax.swing.DefaultListModel;

/**
 *
 * @author robertoarmas
 */
public class ConsultarForm extends javax.swing.JFrame {

    private DefaultListModel registroModel;
    private Lista registroListObject;
    private Asiento asientoSelected;

    /**
     * Creates new form ConsultarForm
     */
    public ConsultarForm() {
        initComponents();
        registroModel = new DefaultListModel();
        
        new GestorInformacion("registro") {

            @Override
            public void didGetData(Lista datos) {
                registroListObject = datos;
                for (int i = 0; i < datos.size(); i++) {
                    registroModel.addElement(((Registro) datos.get(i)).getCliente().getCedula() + " - " + ((Registro) datos.get(i)).getAsiento().getName() + " - " + ((Registro) datos.get(i)).getHora().getHora() + " - " + ((Registro) datos.get(i)).getHora().getAvion().getNombre() + " - " + ((Registro) datos.get(i)).getStatus());
                }
            }

            @Override
            public void didFailLoad(String message) {

            }
        };

        this.registroList.setModel(registroModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        registroList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        cancelarVuelo = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        cedulaBtnSearch = new javax.swing.JButton();
        cedulaTxtField = new javax.swing.JTextField();
        actualizarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(registroList);

        jLabel1.setText("Registro de Vuelos");

        cancelarVuelo.setText("Cancelar Vuelo");
        cancelarVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarVueloMouseClicked(evt);
            }
        });

        closeBtn.setText("Cerrar");
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        cedulaBtnSearch.setText("Buscar por Cédula");
        cedulaBtnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaBtnSearchMouseClicked(evt);
            }
        });
        cedulaBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaBtnSearchActionPerformed(evt);
            }
        });

        actualizarBtn.setText("Actualizar");
        actualizarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualizarBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cedulaBtnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarVuelo)
                            .addComponent(actualizarBtn)
                            .addComponent(closeBtn))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaBtnSearch)
                    .addComponent(cedulaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelarVuelo)
                        .addGap(7, 7, 7)
                        .addComponent(actualizarBtn)
                        .addGap(18, 18, 18)
                        .addComponent(closeBtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarVueloMouseClicked
        // TODO add your handling code here:
        if (!this.registroList.isSelectionEmpty()) {
            asientoSelected = ((Registro) registroListObject.get(registroList.getSelectedIndex())).getAsiento();
            asientoSelected.setDisponible(true);
            ((Registro) registroListObject.get(registroList.getSelectedIndex())).setStatus(false);
            new GestorInformacion("registro", "w", registroListObject) {

                @Override
                public void didGetData(Lista datos) {
                    new GestorInformacion("asiento") {

                        @Override
                        public void didGetData(Lista datos) {
                            for (int i = 0; i < datos.size(); i++) {
                                if (asientoSelected.getId() == ((Asiento) datos.get(i)).getId()) {
                                    datos.getNode(i).setDato(asientoSelected);
                                }
                            }
                            guardarAsientos(datos);

                        }

                        @Override
                        public void didFailLoad(String message) {

                        }

                    };

                }

                @Override
                public void didFailLoad(String message) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
            };

        }

    }//GEN-LAST:event_cancelarVueloMouseClicked

    private void cedulaBtnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulaBtnSearchMouseClicked
        // TODO add your handling code here:
        registroModel.removeAllElements();
        for (int i = 0; i < this.registroListObject.size(); i++) {
            if (this.cedulaTxtField.getText().compareTo(((Registro) registroListObject.get(i)).getCliente().getCedula()) == 0) {
                registroModel.addElement(((Registro) registroListObject.get(i)).getCliente().getCedula() + " - " + ((Registro) registroListObject.get(i)).getAsiento().getName() + " - " + ((Registro) registroListObject.get(i)).getHora().getHora() + " - " + ((Registro) registroListObject.get(i)).getHora().getAvion().getNombre() + " - " + ((Registro) registroListObject.get(i)).getStatus());
            }
        }
    }//GEN-LAST:event_cedulaBtnSearchMouseClicked

    private void actualizarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarBtnMouseClicked
        // TODO add your handling code here:
        this.cedulaTxtField.setText("");
        this.updateList();
    }//GEN-LAST:event_actualizarBtnMouseClicked

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        App app = new App();
        app.show();
        this.dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void cedulaBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaBtnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaBtnSearchActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed
    private void guardarAsientos(Lista asientos) {

        new GestorInformacion("asiento", "w", asientos) {

            @Override
            public void didGetData(Lista datos) {
                System.out.println("Guardo");
                updateList();
            }

            @Override
            public void didFailLoad(String message) {
                System.out.println("Error");
            }

        };
    }

    private void updateList() {
        registroModel.removeAllElements();
        for (int i = 0; i < this.registroListObject.size(); i++) {
            registroModel.addElement(((Registro) registroListObject.get(i)).getCliente().getCedula() 
            + " - " + ((Registro) registroListObject.get(i)).getAsiento().getName() + " - " 
            + ((Registro) registroListObject.get(i)).getHora().getHora() 
            + " - " + ((Registro) registroListObject.get(i)).getHora().getAvion().getNombre() 
            + " - " + ((Registro) registroListObject.get(i)).getStatus());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBtn;
    private javax.swing.JButton cancelarVuelo;
    private javax.swing.JButton cedulaBtnSearch;
    private javax.swing.JTextField cedulaTxtField;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList registroList;
    // End of variables declaration//GEN-END:variables
}
